### ISSUE TITLE
Name Error

### ISSUE THREAD

**Issue by LongchaoDa** [coco11563/Group-wise-Reinforcement-Feature-Generation-for-Optimal-and-Explainable-Representation-Space-Reconst#1]
Dear authors, 

Thanks for the awesome project, I encountered a problem while implementing the repository: 

NameError: name `state_dim` is not defined

This happens after executing the following command: 

`python3 main.py --name airfoil --episodes 30 --steps 15`

**Comment by coco11563** [comment]
we have address this issue, please update the code
